version: "3.7"

services:
  router:
    build: .services/router
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:8080
    restart: always

  portainer:
    image: portainer/portainer
    volumes:
      - portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9000:9000
    environment:
      DOCKER_CLIENT_TIMEOUT: 60
    restart: always

  home:
    build: .services/home
    labels:
      - "traefik.http.routers.whoami.rule=Host(`whoami.docker.localhost`)"

  whoami:
    image: containous/whoami

volumes:
  portainer: ~
