version: "3.7"

services:
  dns:
    build: .services/dns
    ports:
      - "53:53"
      - "53:53/udp"

  router:
    build: .services/router
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "80:80"
      - "81:8080"
    restart: always

  portainer:
    image: portainer/portainer
    volumes:
      - portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DOCKER_CLIENT_TIMEOUT: 60
    restart: always
    labels:
      - traefik.http.services.portainer-desktop.loadbalancer.server.port=9000

  home:
    build: .services/home

  whoami:
    image: containous/whoami

volumes:
  portainer: ~
