HYPHEN_INSENSITIVE="true"
HIST_STAMPS="yyyy-mm-dd"
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=10'

export PATH="${HOME}/.zsh/bin:${HOME}/.gem/bin:${PATH}"

export EMOJI_CLI_KEYBIND="^e"

export TMUXIFIER_LAYOUT_PATH="${HOME}/.tmuxifier/layouts"

export ZPLUG_THREADS=64

setopt HIST_IGNORE_ALL_DUPS
setopt HIST_SAVE_NO_DUPS
setopt HIST_REDUCE_BLANKS
