[options]
  bootstrap_before = "bootstrap#before"
  colorscheme = "gruvbox"
  colorscheme_bg = "dark"
  enable_guicolors = true
  statusline_separator = "nil"
  statusline_inactive_separator = "nil"
  buffer_index_type = 4
  enable_tabline_filetype_icon = true
  enable_statusline_mode = false

[[layers]]
  name = "autocomplete"
  auto-completion-return-key-behavior = "complete"
  auto-completion-tab-key-behavior = "smart"

[[layers]]
  name = "shell"
  default_position = "top"
  default_height = 30

[[layers]]
  name = "lang#php"

[[layers]]
  name = "lang#go"
